In [2]:
import pandas as pd
import numpy as np

In [3]:
# 1
data_students = {
    'Name': ['Kaushal', 'Ansh', 'Parth', 'Hemant'],
    'Age':[19,20,18,21],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
student_df = pd.DataFrame(data_students)
print(student_df)

      Name  Age         City
0  Kaushal   19     New York
1     Ansh   20  Los Angeles
2    Parth   18      Chicago
3   Hemant   21      Houston

In [4]:
#2
print(student_df)

      Name  Age         City
0  Kaushal   19     New York
1     Ansh   20  Los Angeles
2    Parth   18      Chicago
3   Hemant   21      Houston

In [5]:
#3
print(student_df.columns)

Index(['Name', 'Age', 'City'], dtype='object')

In [6]:
#4
name_col = student_df['Name']
print(name_col)

0    Kaushal
1       Ansh
2      Parth
3     Hemant
Name: Name, dtype: object

In [7]:
#5
city_col = student_df['City']
print(city_col)

0       New York
1    Los Angeles
2        Chicago
3        Houston
Name: City, dtype: object

In [8]:
#6
name_city_df = student_df[['Name', 'City']]
print(name_city_df)

      Name         City
0  Kaushal     New York
1     Ansh  Los Angeles
2    Parth      Chicago
3   Hemant      Houston

In [9]:
#7
books_df = pd.DataFrame({
    'Book': ['Ramayan', 'merchant of venice', 'Numpy'],
    'Author': ['Tulsidas', 'william shakespeare', 'Pratikshit Pandey'],
    'Price': [799.99, 299.99, 78.50]
})
print(books_df)

                 Book               Author   Price
0             Ramayan             Tulsidas  799.99
1  merchant of venice  william shakespeare  299.99
2               Numpy    Pratikshit Pandey   78.50

In [10]:
#8
books_df['Publisher'] = ['Gorkhpur Publication','Hindustan Publications','GLA Publications']
print(books_df)

                 Book               Author   Price               Publisher
0             Ramayan             Tulsidas  799.99    Gorkhpur Publication
1  merchant of venice  william shakespeare  299.99  Hindustan Publications
2               Numpy    Pratikshit Pandey   78.50        GLA Publications

In [11]:
#9
df_five_rows = pd.DataFrame(index=range(5))
df_five_rows['SerialNo'] = np.arange(5)
print(df_five_rows)

   SerialNo
0         0
1         1
2         2
3         3
4         4

In [12]:
#10
del df_five_rows['SerialNo']
print(df_five_rows)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [13]:
#11
data_movies = {
    'Movie': ['Inception', 'Interstellar', 'The Dark Knight'],
    'Year':[2002,2004,2006],
    'Rating': [8.8, 8.6, 9.0]
}
movie_df = pd.DataFrame(data_movies)
print(movie_df)

             Movie  Year  Rating
0        Inception  2002     8.8
1     Interstellar  2004     8.6
2  The Dark Knight  2006     9.0

In [14]:
#12
new_movie_df = movie_df.reindex(columns=['Movie', 'Rating', 'Director'])
print(new_movie_df)

             Movie  Rating  Director
0        Inception     8.8       NaN
1     Interstellar     8.6       NaN
2  The Dark Knight     9.0       NaN

In [15]:
#13
city_series = pd.Series(['Boston', 'Seattle'], index=[0, 3])
print(city_series)

0     Boston
3    Seattle
dtype: object

In [16]:
#14
df = pd.DataFrame({'Name': ['X', 'Y', 'Z', 'W']})
df['Branch'] = city_series
print(df)

  Name   Branch
0    X   Boston
1    Y      NaN
2    Z      NaN
3    W  Seattle

In [17]:
# 16
emp_data = {
    'Employee': ['John', 'Anna', 'Peter', 'Linda', 'Tom'],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'IT'],
    'Experience': [5, 3, 8, 2, 6]
}
employee_df = pd.DataFrame(emp_data)
emp_df = employee_df[['Employee', 'Experience']]
emp_df

  Employee  Experience
0     John           5
1     Anna           3
2    Peter           8
3    Linda           2
4      Tom           6

In [18]:
#17
print(employee_df['Department'])
print(employee_df.columns)

0           HR
1           IT
2      Finance
3    Marketing
4           IT
Name: Department, dtype: object
Index(['Employee', 'Department', 'Experience'], dtype='object')

In [19]:
#18
employee_df['Office'] = 'Head Office'
employee_df

  Employee Department  Experience       Office
0     John         HR           5  Head Office
1     Anna         IT           3  Head Office
2    Peter    Finance           8  Head Office
3    Linda  Marketing           2  Head Office
4      Tom         IT           6  Head Office

In [20]:
#19
employee_df['Office'] = np.arange(5)
employee_df

  Employee Department  Experience  Office
0     John         HR           5       0
1     Anna         IT           3       1
2    Peter    Finance           8       2
3    Linda  Marketing           2       3
4      Tom         IT           6       4

In [21]:
#20
office_names = pd.Series(['Delhi', 'Mumbai', 'Pune'], index=[0, 2, 4])
employee_df['Office'] = office_names
employee_df

  Employee Department  Experience  Office
0     John         HR           5   Delhi
1     Anna         IT           3     NaN
2    Peter    Finance           8  Mumbai
3    Linda  Marketing           2     NaN
4      Tom         IT           6    Pune

In [22]:
#21
del employee_df['Office']
employee_df

  Employee Department  Experience
0     John         HR           5
1     Anna         IT           3
2    Peter    Finance           8
3    Linda  Marketing           2
4      Tom         IT           6

In [23]:
#22
p_data = {
    'Product': ['Laptop', 'Phone', 'Desk'],
    'Category': ['Electronics', 'Electronics', 'Furniture'],
    'Price': [1000, 500, 150]
}
product_df = pd.DataFrame(p_data)
prod_df = product_df[['Price', 'Product', 'Category']]
prod_df

   Price Product     Category
0   1000  Laptop  Electronics
1    500   Phone  Electronics
2    150    Desk    Furniture

In [24]:
#23
const_df = pd.DataFrame(product_df, columns=['Product', 'Price', 'Category', 'Stock'])
const_df

  Product  Price     Category  Stock
0  Laptop   1000  Electronics    NaN
1   Phone    500  Electronics    NaN
2    Desk    150    Furniture    NaN

In [25]:
#24
marks_df = pd.DataFrame({'Student': ['A', 'B'], 'Total Marks': [85, 92]})
marks_df['Total Marks'] = marks_df['Total Marks']
marks_df['Total Marks']

0    85
1    92
Name: Total Marks, dtype: int64

In [26]:
#26
course_data = {
    'Student': ['Sam', 'Kim', 'Alex', 'Chris', 'Pat'],
    'Course': ['Math', 'Sci', 'Math', 'Eng', 'Sci'],
    'Score': [90, 85, 88, 92, 79]
}
course_df = pd.DataFrame(course_data)
print(course_df.columns)
print( course_df['Student'])
student_score_df = course_df[['Student', 'Score']]
print(student_score_df)
course_df['Batch'] = '2026-A'
print( course_df)

Index(['Student', 'Course', 'Score'], dtype='object')
0      Sam
1      Kim
2     Alex
3    Chris
4      Pat
Name: Student, dtype: object
  Student  Score
0     Sam     90
1     Kim     85
2    Alex     88
3   Chris     92
4     Pat     79
  Student Course  Score   Batch
0     Sam   Math     90  2026-A
1     Kim    Sci     85  2026-A
2    Alex   Math     88  2026-A
3   Chris    Eng     92  2026-A
4     Pat    Sci     79  2026-A

In [27]:
#27
travel_df = pd.DataFrame({'Destination': ['Paris', 'Tokyo', 'Rome', 'New York', 'Sydney']})
travel_df['Code'] = np.arange(5)
print(travel_df)
part_series = pd.Series([101, 404], index=[1, 4])
travel_df['Code'] = part_series
print(travel_df)

  Destination  Code
0       Paris     0
1       Tokyo     1
2        Rome     2
3    New York     3
4      Sydney     4
  Destination   Code
0       Paris    NaN
1       Tokyo  101.0
2        Rome    NaN
3    New York    NaN
4      Sydney  404.0

In [28]:
#28
school_data = {
    'Student': ['Liam', 'Noah', 'Oliver'],
    'Class': [10, 11, 10],
    'Section': ['A', 'B', 'A']
}
school_df = pd.DataFrame(school_data)
ext_school_df = pd.DataFrame(school_df, columns=['Student', 'Class', 'Section', 'House'])
print(ext_school_df)
ext_school_df['House'] = 'Red House'
print(ext_school_df)

  Student  Class Section  House
0    Liam     10       A    NaN
1    Noah     11       B    NaN
2  Oliver     10       A    NaN
  Student  Class Section      House
0    Liam     10       A  Red House
1    Noah     11       B  Red House
2  Oliver     10       A  Red House

In [29]:
#29
items = ["Laptops", "Desktops", "Monitors", "Keyboards", "Mice"]
quantity = [15, 8, 24, 50, 45]
prices = [800, 600, 150, 30, 20]
inventory_df = pd.DataFrame({"Item": items, "Quantity": quantity, "Price": prices})
restock_notes = pd.Series(["Urgent", "Sufficient", "Critical"], index=[0, 2, 4])
inventory_df["Restock_Status"] = restock_notes
print(inventory_df)
del inventory_df["Restock_Status"]
print(inventory_df)

        Item  Quantity  Price Restock_Status
0    Laptops        15    800         Urgent
1   Desktops         8    600            NaN
2   Monitors        24    150     Sufficient
3  Keyboards        50     30            NaN
4       Mice        45     20       Critical
        Item  Quantity  Price
0    Laptops        15    800
1   Desktops         8    600
2   Monitors        24    150
3  Keyboards        50     30
4       Mice        45     20